### ISSUE TITLE
Posible error de dependencia

### ISSUE THREAD

**Issue by tatuguerra** [ctt-gob-es/oaw#19]
Acabo de compilar el OAW. Pero fallaba al final al hacer el test en el PDFTOCManagaerTest en la linea 3
"import com.lowagie.text.pdf.events.IndexEvents;"

He visto en el POM que estaba comentada la dependencia com.lowagie y que parece que habéis cambiado por el com.itextpdf.

Para arreglarlo yo cambié en el test por
"import com.itextpdf.text.pdf.events.IndexEvents;"
y me ha funcionado.

Un saludo,

**Comment by alvaropelaezctic** [comment]
Se corrije el cambio tras actualizar la dependencia que no se había propagado a todos los test.
