### ISSUE TITLE
Error de compilación - oaw 5.1.0

### ISSUE THREAD

**Issue by jolr** [ctt-gob-es/oaw#26]
Buenas tardes.

Estoy tratando de compilar el proyecto en la última release publicada v5.1.0 y sale los siguientes errores al no encontrar referencias a métodos:
`[ERROR]     E extends Object declared in interface Iterator
[ERROR] .../oaw-5.1.0/portal/src/main/java/es/gob/oaw/basicservice/BasicServiceManager.java:[227,50] error: cannot find symbol
[ERROR]  class TAnalisisAccesibilidadDAO
[ERROR] .../oaw-5.1.0/portal/src/main/java/es/gob/oaw/basicservice/BasicServiceManager.java:[229,25] error: cannot find symbol
`

La configuración utlizada para compilada es:
`$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: ...apache-maven-3.6.3
Java version: 1.8.0_282, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: es_ES, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-49-generic", arch: "amd64", family: "unix"`

Gracias, saludos.

**Comment by heroma** [comment]
Buenas tardes,

Tenemos el mismo problema.

En relación con este error, los métodos getSourceCode ([línea 227](https://github.com/ctt-gob-es/oaw/blob/6787090e63c84ad6bf28c315bddfd65ac0c283cb/portal/src/main/java/es/gob/oaw/basicservice/BasicServiceManager.java#L227)) y writeSourceFilesAccessibility ([línea 229](https://github.com/ctt-gob-es/oaw/blob/6787090e63c84ad6bf28c315bddfd65ac0c283cb/portal/src/main/java/es/gob/oaw/basicservice/BasicServiceManager.java#L229)) pertenece al branch 5.2.0 de las clases TAnalisisAccesibilidadDAO y SourceFilesManager respectivamente pero no van incluídos en esta versión 5.1.0:

- https://github.com/ctt-gob-es/oaw/commit/a548822d7d520e4724dcb97553700aee57346f24#diff-a7c2fe9c2ffcc2c1a312905f6916e31b6e59d1592338e18e0fe08386d0bea8da
- https://github.com/ctt-gob-es/oaw/commit/a548822d7d520e4724dcb97553700aee57346f24#diff-3784504eb296fd783dc9c27b037616201cfe4407a67255cd29a7c9254c51d2b5

Para poder compilar esta versión 5.1.0 ¿qué será preferible eliminar esa parte del código (líneas 225 a 231) del BasicServiceManager.java o descargar el SourceFilesManager.java y el TAnalisisAccesibilidadDAO.java del branch 5.2.0?

Saludos.

**Comment by jolr** [comment]
Corregido en el último commit por lo que veo https://github.com/ctt-gob-es/oaw/commit/5fa68a4249d4ae000d192f8859049bab503770b2

Cierro la issue.

Gracias.
